- README.md
small typos correction for readme file
> REFACTOR: set code into code cells

- .travis.yml
- continuous_integration/install.sh
- continuous_integration/tests.sh
CI via travis with anaconda following the structure proposed by nilearn
> UPDATE : continuous integration via anaconda

- slam/generate_parametric_surfaces.py
Add an (almost) regular sampling of a paraboloid in generate_parametric_surfaces.py :
- auxiliary function: adaptive_sampling.py
- principal function : generate_paraboloid_regular.py
> Parabolid regular

- slam/plot.py
Very minor modifications for pyglet_plot. 
Maybe it is better to wait for other modifications, in particular when ColorbarBase will work :-)
> Colorbar in pyglet_plot

- slam/topology.py
- tests/test_curvature.py
test case + new code for adjacency matrix
> Adjacency matrix

- mes_examples/example_curvature.py
Correct a bug in array dimensions to compute angular erros
> Example curvature

- examples/example_surface_profiling.py
- slam/surface_profiling.py
- slam/utils.py
- tests/test_surface_profiling.py
> surface_profiling

- examples/README.txt
- examples/example_surface_profiling.py
add an example of surface profiling
> Surface profiling

- setup.py
- slam/io.py
Used new nibabel api for meshes IO
> REFACTOR: used new nibabel api (>2.1)

- slam/plot.py
Hi, this a proposition of change to add clim setting to the visbrain_plot function
> adding clim setting to visbrain_plot function

- examples/example_dpf_Boucher.py
- slam/differential_geometry.py
- slam/generate_parametric_surfaces.py
- slam/plot.py
Hello,
The main contribution of this PR is related to the implementation of an example provided in _Depth potential function for folding pattern representation, registration and analysis, Maxime Boucher, Sue Whitesides, Alan Evans, Medical Image Analysis, 2009_ :
- Define a parametric surface depending on two parameters M and sigma. This surface is a second-order derivative in y direction with standard deviation sigma) and a gaussian in x direction. Amplitude is encoded by M. So it can be seen as schematic representation for a cortical fold.
- Compute the depth potential function by using Laplacian discretization and Rusinkiewicz curvature as proposed in brain-slam
- Make vary the parameter alpha used to compute the DPF and look at the evolution of the DPF at the center (negative peak) …
> Example for depth potential function as described in Boucher et al, MedIA 2009

- doc/whats_new.rst
The purpose of the file : whats_new.rst is to tracking all the versioning, highlight, fixes and enhancements.
Once a pull request is accepted, we add what is new in the what_news :)
https://www.youtube.com/watch?v=SsXprfyx99w
> [ENH] added a tracking file change (whats_new.rst) in the doc directory

- slam/curvature.py
- tests/test_curvature.py
Hello,
I have rewritten and commented determine_local_basis in curvature.py . I also removed the proj_matrix inside curvature_fit since it was used only to compute the local basis.
> rewrite and comment determine_local_basis

- tests/test_io.py
modified relative spheres path to allow the tests to pass
> [BF]: fixed path in test_io.py

- slam/spangy.py
This PR is just to set up the structure of the module, unittest and example script.
We will improve all these pieces of code tomorrow.
> initial setup for the implementation of spangy

- slam/mapping.py
- slam/spangy.py
- slam/utils.py
- slam/vertex_voronoi.py
General linting of the mapping module
> LINTING mapping module

- slam/spangy.py
Keep on doing linting on the spangy module
> Spangy lint

- examples/example_spangy.py
- slam/generate_parametric_surfaces.py
- slam/spangy.py
- tests/test_spangy.py
One unit test for spangy still needs to be fixed (for local_dominance_map). Moreover, some fixes applied to the same function in the spangy module. 
Passes linter and unit tests locally.
> Spangy - Added two unit tests, fixed small issues

- .github/workflows/continuous_integration.yml
- examples/example_curvature.py
- examples/example_dpf_Boucher.py
- examples/example_mapping.py
- examples/example_profile_texture.py
- examples/example_topology.py
- slam/curvature.py
- slam/differential_geometry.py
- slam/geodesics.py
- slam/io.py
- slam/remeshing.py
- slam/surface_profiling.py
- slam/topology.py
- tests/test_curvature.py
General linting of the core code to avoid failing linting tests
> [LINTING]: general linting to avoid crash during CI

- slam/io.py
Hi, 
The io/load_texture function does not work, we changed how to load it.
Best
Steven, Mattia, Baptiste and Angie
> Fixed bug io/load_texture
